version: '3.8'

services:
  api:
    container_name: tender_positions_match_service
    build: .
    ports:
      - "8002:8000"
    env_file:
      - .env
    environment:
      # API
      - API_KEY=${API_KEY}

      - SERVICE_PORT=8000
      # External MongoDB connection
      - UNIQUE_MONGO_HOST=${UNIQUE_MONGO_HOST}
      - UNIQUE_MONGO_PORT=${UNIQUE_MONGO_PORT}
      - UNIQUE_MONGO_USER=${UNIQUE_MONGO_USER}
      - UNIQUE_MONGO_PASS=${UNIQUE_MONGO_PASS}
      - UNIQUE_MONGO_AUTHSOURCE=${UNIQUE_MONGO_AUTHSOURCE:-admin}
      - UNIQUE_MONGO_AUTHMECHANISM=${UNIQUE_MONGO_AUTHMECHANISM:-SCRAM-SHA-256}
      - UNIQUE_MONGODB_DATABASE=${UNIQUE_MONGODB_DATABASE}
      - UNIQUE_COLLECTION_NAME=${UNIQUE_COLLECTION_NAME}

      # Processing settings
      - MIN_MATCH_SCORE=${MIN_MATCH_SCORE:-0.5}
      - MAX_MATCHED_PRODUCTS_PER_ITEM=${MAX_MATCHED_PRODUCTS_PER_ITEM:-20}
      - PRICE_TOLERANCE_PERCENT=${PRICE_TOLERANCE_PERCENT:-20.0}
    networks:
      - tender-services

    volumes:
      - ./logs:/app/logs
    restart: unless-stopped

networks:
  tender-services:
    external: true