version: '3.8'

services:
  tender-matching:
    build: .
    container_name: tender-matching-service
    ports:
      - "8002:8002"
    environment:
      # API
      - API_KEY=${API_KEY}
      - SERVICE_NAME=tender_matching_service
      - SERVICE_PORT=8002

      # External MongoDB connection
      - UNIQUE_MONGO_HOST=${UNIQUE_MONGO_HOST}
      - UNIQUE_MONGO_PORT=${UNIQUE_MONGO_PORT}
      - UNIQUE_MONGO_USER=${UNIQUE_MONGO_USER}
      - UNIQUE_MONGO_PASS=${UNIQUE_MONGO_PASS}
      - UNIQUE_MONGO_AUTHSOURCE=${UNIQUE_MONGO_AUTHSOURCE:-admin}
      - UNIQUE_MONGO_AUTHMECHANISM=${UNIQUE_MONGO_AUTHMECHANISM:-SCRAM-SHA-256}
      - UNIQUE_MONGODB_DATABASE=${UNIQUE_MONGODB_DATABASE}
      - UNIQUE_COLLECTION_NAME=${UNIQUE_COLLECTION_NAME}

      # Processing settings
      - MIN_MATCH_SCORE=${MIN_MATCH_SCORE:-0.5}
      - MAX_MATCHED_PRODUCTS_PER_ITEM=${MAX_MATCHED_PRODUCTS_PER_ITEM:-20}
      - PRICE_TOLERANCE_PERCENT=${PRICE_TOLERANCE_PERCENT:-20.0}

    volumes:
      - ./logs:/app/logs
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8002/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s